### ISSUE TITLE
Lab report 4 Feedback

### ISSUE THREAD

**Issue by shad674** [agurel33/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:

Feel free to comment below any questions about the rubric/feedback:

`Decide on what it should produce by using either VScode preview or [the CommonMark demo site](https://spec.commonmark.org/dingus/)`  <- missing

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by agurel33** [comment]
Hey, I just wanted to ask if you could clarify what I am missing. Below each code block for each snippet 1, 2, and 3, I wrote a sentence explaining what the expected outcome should be, and I also have screenshots of all of my tests and all of the tests for the reviewed repository, and also included screenshots of their errors/the terminal which also shows the expected output. If you could specify what exactly is missing from this lab report, I will then do my best to fix it. Thank you!

**Comment by shad674** [comment]
What I mean by that is that, did you check the expected output by using the the common mark demo site? if so are there any evidence that those expected output are what it produces? (meaning taking screenshot and showing us the evidence)

**Comment by agurel33** [comment]
Okay, thank you! I fixed what you suggested, and I just wanted to ask when the regrade request on Gradescope is going to open up.

**Comment by shad674** [comment]
good job! I'll fix your grade
